theme: jekyll-theme-minimal
title: nthonybruno
name: InfoSec Blog
description: CySec Blog
google_analytics: G-2D2C6EGVHW
avatar: https://avatars.githubusercontent.com/u/44067716?v=4
show_downloads: true
logo: https://avatars.githubusercontent.com/u/44067716?v=4
